# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PGMac . Net . AU
email: pgmac@pgmac.net
description: > # this means to ignore newlines until "baseurl:"
  Where I think about things and make the internet listen. Because it's important.
baseurl: ""
url: "https://pgmac.net.au" # the base hostname & protocol for your site
twitter_username: pmacdonnell
github_username:  pgmac
paginate: 5

# Build settings
markdown: kramdown
plugins_dir: _scripts
gems:
  - jekyll-paginate
